Repository OSLL/code-plagiarism, pull requests merged in 2025-05, with the labels that each got.

#226 refactor: adds an information column into the general report about the type of compare.
  .gitignore
  Makefile
  locales/codeplag.pot
  locales/translations/en/LC_MESSAGES/codeplag.po
  locales/translations/ru/LC_MESSAGES/codeplag.po
  src/templates/general.templ
Labels: Refactoring

#227 feat: adds trace logging level for more debug info when needed.
  Makefile
  src/codeplag/handlers/check.py
  src/codeplag/logger.py
  src/codeplag/types.py
  test/auto/functional/test_settings.py
Labels: enhancement

#229 feat: add mongodb compare_info and ASTFeatures caching
  Makefile
  README.md
  docker/compose.yml
  docker/docker.mk
  locales/codeplag.pot
  locales/translations/en/LC_MESSAGES/codeplag.po
  locales/translations/ru/LC_MESSAGES/codeplag.po
  setup.py
  src/codeplag/codeplagcli.py
  src/codeplag/config.py
  src/codeplag/consts.tmp.py
  src/codeplag/cplag/utils.py
  src/codeplag/db/__init__.py
  src/codeplag/db/mongo.py
  src/codeplag/featurescache.py
  src/codeplag/getfeatures.py
  src/codeplag/handlers/check.py
  src/codeplag/pyplag/utils.py
  src/codeplag/reporters.py
  src/codeplag/types.py
  test/auto/functional/test_mongo.py
  test/auto/functional/test_settings.py
  test/auto/utils.py
  test/unit/codeplag/db/__init__.py
  test/unit/codeplag/db/test_mongo.py
  test/unit/codeplag/db/testkit.py
  test/unit/codeplag/test_config.py
  test/unit/codeplag/test_featurescache.py
  test/unit/codeplag/test_reporters.py
Labels: enhancement, tests, Hard, moevm
